/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import javax.swing.JOptionPane;
import javax.swing.JInternalFrame;
import service.LoginService;

public class loginForm extends JInternalFrame {

    public loginForm() {
        initComponents();
        this.setClosable(true);
        this.setResizable(false);
        this.setTitle("Login");
    }

    private void login() {
        String email = utilisateur.getText();
        String password = new String(motdepasse.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir l'email et le mot de passe !");
            return;
        }

        LoginService ls = new LoginService();
        if (ls.checkLogin(email, password)) {
            JOptionPane.showMessageDialog(this, "Connexion réussie !");
            this.dispose(); // ferme le JInternalFrame
        } else {
            JOptionPane.showMessageDialog(this, "Email ou mot de passe incorrect !");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        utilisateur = new javax.swing.JTextField();
        connecter = new javax.swing.JButton();
        motdepasseoublier = new javax.swing.JButton();
        motdepasse = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Connexion");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("Nom d'utilisateur    :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel3.setText("Mot de passe          :");

        utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateurActionPerformed(evt);
            }
        });

        connecter.setBackground(new java.awt.Color(204, 153, 255));
        connecter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        connecter.setText("connecter");
        connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecterActionPerformed(evt);
            }
        });

        motdepasseoublier.setBackground(new java.awt.Color(204, 153, 255));
        motdepasseoublier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        motdepasseoublier.setText("mot de passe oublie");
        motdepasseoublier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motdepasseoublierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(motdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(motdepasseoublier, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(connecter, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(motdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(connecter)
                .addGap(44, 44, 44)
                .addComponent(motdepasseoublier)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilisateurActionPerformed

    private void connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecterActionPerformed
        
   String identifier = utilisateur.getText().trim(); // Peut être username ou email
    String password = new String(motdepasse.getPassword()).trim();

    if (identifier.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Veuillez saisir le nom d'utilisateur/email et le mot de passe !",
            "Champs vides",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    LoginService ls = new LoginService();
    if (ls.checkLogin(identifier, password)) {
        JOptionPane.showMessageDialog(this, 
            " Connexion réussie !",
            "Succès",
            JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, 
            " Identifiant ou mot de passe incorrect !\n" +
            "Utilisateur : admin\n" +
            "Mot de passe : admin",
            "Échec de connexion",
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_connecterActionPerformed

    private void motdepasseoublierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motdepasseoublierActionPerformed
       String email = JOptionPane.showInputDialog(this, 
        "Veuillez saisir votre email de récupération :", 
        "Mot de passe oublié", 
        JOptionPane.QUESTION_MESSAGE);
    
    if (email == null || email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Email non saisi. Opération annulée.", 
            "Annulé", 
            JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    email = email.trim();
    
    if (!email.contains("@") || !email.contains(".")) {
        JOptionPane.showMessageDialog(this, 
            "Format d'email invalide !", 
            "Erreur", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
        "Êtes-vous sûr de vouloir réinitialiser le mot de passe pour :\n" + email + " ?",
        "Confirmation",
        JOptionPane.YES_NO_OPTION);
    
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    LoginService ls = new LoginService();
    if (!ls.checkUserExists(email)) {
        JOptionPane.showMessageDialog(this, 
            "Email introuvable dans la base de données !\n" +
            "Vérifiez l'email saisi.", 
            "Erreur", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    ls.resetPassword(email);
    }//GEN-LAST:event_motdepasseoublierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField motdepasse;
    private javax.swing.JButton motdepasseoublier;
    private javax.swing.JTextField utilisateur;
    // End of variables declaration//GEN-END:variables
}
