/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import service.VenteService;

/**
 *
 * @author Lenovo
 */
public class Mainform extends javax.swing.JFrame {
public javax.swing.JDesktopPane getDesktopPane() {
    return desktopPane;
}

    /**
     * Creates new form Mainform
     */
    public Mainform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ProduitMenuItem = new javax.swing.JMenuItem();
        VenteMenuItem = new javax.swing.JMenuItem();
        clientMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        categorieMenuItem = new javax.swing.JMenuItem();
        periodeMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        chiffreAffairesparmois = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        ProduitMenuItem.setMnemonic('s');
        ProduitMenuItem.setText("Produit");
        ProduitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ProduitMenuItem);

        VenteMenuItem.setMnemonic('a');
        VenteMenuItem.setText("Vente");
        VenteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenteMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(VenteMenuItem);

        clientMenuItem.setMnemonic('o');
        clientMenuItem.setText("Client");
        clientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(clientMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Filtrage");

        categorieMenuItem.setMnemonic('t');
        categorieMenuItem.setText("Categorie");
        categorieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(categorieMenuItem);

        periodeMenuItem.setMnemonic('y');
        periodeMenuItem.setText("Periode");
        periodeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodeMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(periodeMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statigue");

        chiffreAffairesparmois.setMnemonic('c');
        chiffreAffairesparmois.setText("chiffre d'affaires par mois");
        chiffreAffairesparmois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiffreAffairesparmoisActionPerformed(evt);
            }
        });
        helpMenu.add(chiffreAffairesparmois);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientMenuItemActionPerformed
      
    ClientFormmm cf = new ClientFormmm();

    desktopPane.add(cf);

    cf.setVisible(true);

    }//GEN-LAST:event_clientMenuItemActionPerformed

    private void ProduitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduitMenuItemActionPerformed
        ProduitFormm ps = new ProduitFormm();
      desktopPane.add(ps);
     ps.setVisible(true);
    }//GEN-LAST:event_ProduitMenuItemActionPerformed

    private void VenteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenteMenuItemActionPerformed
        // TODO add your handling code here:
         venteForm vf = new venteForm();
      desktopPane.add(vf);
     vf.setVisible(true);
    }//GEN-LAST:event_VenteMenuItemActionPerformed

    private void categorieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieMenuItemActionPerformed
        // TODO add your handling code here:
        RechercheCategorie rc = new RechercheCategorie();
      desktopPane.add(rc);
     rc.setVisible(true);
    }//GEN-LAST:event_categorieMenuItemActionPerformed

    private void periodeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodeMenuItemActionPerformed
        // TODO add your handling code here:
        RechechePeriode rp = new RechechePeriode();
      desktopPane.add(rp);
     rp.setVisible(true);
    }//GEN-LAST:event_periodeMenuItemActionPerformed

    private void chiffreAffairesparmoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiffreAffairesparmoisActionPerformed
    try {
        VenteService vs = new VenteService();
        Map<String, Double> data = vs.getChiffreAffairesParMois();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (String mois : data.keySet()) {
            dataset.addValue(data.get(mois), "Chiffre d'affaires", mois);
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Chiffre d'affaires par Mois",
                "Mois",
                "Chiffre d'affaires (DH)",
                dataset
        );

        ChartPanel panel = new ChartPanel(chart);
        panel.setSize(800, 600);

        javax.swing.JInternalFrame frame = new javax.swing.JInternalFrame(
                "Statistiques CA", true, true, true, true);
        frame.add(panel);
        frame.pack();
        frame.setVisible(true);

        desktopPane.add(frame);
    } catch (Exception e) {
        e.printStackTrace();
    }
                                                       

    }//GEN-LAST:event_chiffreAffairesparmoisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Mainform main = new Mainform();
main.setVisible(true);

loginForm login = new loginForm();
main.getDesktopPane().add(login);
login.setVisible(true);


        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ProduitMenuItem;
    private javax.swing.JMenuItem VenteMenuItem;
    private javax.swing.JMenuItem categorieMenuItem;
    private javax.swing.JMenuItem chiffreAffairesparmois;
    private javax.swing.JMenuItem clientMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem periodeMenuItem;
    // End of variables declaration//GEN-END:variables

}
